apiVersion: v1
kind: Service
metadata:
  name: mumble
  namespace: mumble
  labels:
    app: mumble
spec:
  type: LoadBalancer
  ports:
  - name: mumble-tcp
    port: 64738
    targetPort: 64738
    protocol: TCP
  - name: mumble-udp
    port: 64738
    targetPort: 64738
    protocol: UDP
  selector:
    app: mumble
